/**
 * Photograph + credit for each dish, generated by scripts/fetch-recipe-photos.mjs.
 *
 * These are Pexels photographs. The licence does not require attribution, but
 * the credit is rendered on the site anyway — do not drop it, and do not add
 * an entry without one. Re-run the script rather than editing this file by hand.
 */

export const RECIPE_PHOTOS = {
  "indori-poha": {
    "src": "/recipes/indori-poha.webp",
    "title": "Poha with peanuts and curry leaves, served with a lime wedge",
    "author": "aksinfo7 universe",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/36715858/"
  },
  "dal-tadka": {
    "src": "/recipes/dal-tadka.webp",
    "title": "Dal tadka in a brass-handled kadai, with whole spices",
    "author": "Nosh Caterers",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/30203314/"
  },
  "rajma-chawal": {
    "src": "/recipes/rajma-chawal.webp",
    "title": "Rice and rajma curry on a wooden board",
    "author": "Ali Dashti",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/25856539/"
  },
  "chole-bhature": {
    "src": "/recipes/chole-bhature.webp",
    "title": "Bhature with chole and sides, on a dark ground",
    "author": "Jack Baghel",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/20422122/"
  },
  "shahi-paneer": {
    "src": "/recipes/shahi-paneer.webp",
    "title": "Creamy paneer curry with onion rings and fresh herbs",
    "author": "Dhiraj Jain",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/12737805/"
  },
  "pav-bhaji": {
    "src": "/recipes/pav-bhaji.webp",
    "title": "Pav bhaji garnished with onion, lime and coriander",
    "author": "Saveurs Secretes",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/5410400/"
  },
  "sambhar": {
    "src": "/recipes/sambhar.webp",
    "title": "Sambhar with idli and chutneys, on a dark ground",
    "author": "Jack Baghel",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/20422128/"
  },
  "kadhi-pakora": {
    "src": "/recipes/kadhi-pakora.webp",
    "title": "Kadhi with pakoras and a cumin tempering, in a handi",
    "author": "Pranjall Kumar",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/7161739/"
  },
  "baingan-bharta": {
    "src": "/recipes/baingan-bharta.webp",
    "title": "Baingan bharta garnished with fried onions, served with roti",
    "author": "Shameel mukkath",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/15108368/"
  },
  "masala-chai": {
    "src": "/recipes/masala-chai.webp",
    "title": "Masala chai in clay cups, surrounded by ginger and cardamom",
    "author": "Sanket Sawale",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/20270270/"
  },
  "aloo-chaat": {
    "src": "/recipes/aloo-chaat.webp",
    "title": "Spiced potato chaat with mint, coriander and pomegranate",
    "author": "Nourishment DECODED",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/10585454/"
  },
  "jeera-aloo": {
    "src": "/recipes/jeera-aloo.webp",
    "title": "Jeera aloo in a cast-iron pan, garnished with fresh herbs",
    "author": "Shameel mukkath",
    "licence": "Pexels License",
    "licenceUrl": "https://www.pexels.com/license/",
    "source": "https://www.pexels.com/photo/14883755/"
  }
};

export const photoFor = (slug) => RECIPE_PHOTOS[slug] ?? null;

/** The credit link needs a source name. Read it from the URL rather than
    storing a field that could drift out of sync with `source`. */
export const sourceNameOf = (photo) =>
  photo?.source?.includes("pexels.com") ? "Pexels" : "Wikimedia Commons";
