/**
 * Sunder Masala — catalogue + range taxonomy.
 * Three ranges, three appetites (per the brand strategy deck).
 */

export const RANGES = {
  heritage: {
    id: "heritage",
    name: "Heritage",
    full: "Sunder Heritage",
    who: "The occasion cook",
    line: "From the courts of Awadh, to your table.",
    blurb:
      "Slow-ground, festive, inherited. Recipes handed down — never invented for a trend.",
    voice: ["Heritage", "Hereditary", "Confident", "Sourced"],
    bg: "var(--color-forest)",
    ink: "var(--color-ghee)",
    accent: "var(--color-marigold)",
    tw: { bg: "bg-forest", text: "text-ghee", accent: "text-marigold" },
    icon: "starAnise",
  },
  regions: {
    id: "regions",
    name: "Regions",
    full: "Sunder Regions",
    who: "The rooted foodie",
    line: "Apna region, apni thali.",
    blurb:
      "Hyper-local blends you cannot find on a national shelf. One region, one hero dish, one masala.",
    voice: ["Sarcastic", "Punny", "Intentional"],
    bg: "var(--color-saffron)",
    ink: "var(--color-ink)",
    accent: "var(--color-oxblood)",
    tw: { bg: "bg-saffron", text: "text-ink", accent: "text-oxblood" },
    icon: "thela",
  },
  essentials: {
    id: "essentials",
    name: "Essentials",
    full: "Sunder Essentials · Express",
    who: "The everyday cook",
    line: "Ek chutki, full fire.",
    blurb:
      "Pure, potent, quick-commerce ready. The staple that lives at the front of the spice box.",
    voice: ["Fast", "Punny", "Pure"],
    bg: "var(--color-chilli)",
    ink: "var(--color-paper)",
    accent: "var(--color-marigold)",
    tw: { bg: "bg-chilli", text: "text-paper", accent: "text-marigold" },
    icon: "pinch",
  },
};

export const RANGE_LIST = [RANGES.heritage, RANGES.regions, RANGES.essentials];

export const PRODUCTS = [
  /* ── HERITAGE ─────────────────────────────────────────── */
  {
    slug: "darbari-garam-masala",
    name: "Darbari",
    kind: "Garam Masala",
    range: "heritage",
    tagline: "The crown of every royal dawat.",
    hindi: "दावत-ए-ख़ास, हर निवाले में।",
    badge: "Hero blend",
    price: 265,
    size: "100 g",
    heat: 2,
    grind: "Stone-ground, slow",
    origin: "Awadh × Malwa",
    harvest: "Rabi 2026",
    icon: "starAnise",
    hue: ["#0e3b2c", "#16523c"],
    swatch: "#7a4a12",
    notes: ["Black cardamom", "Cassia bark", "Mace", "Clove", "Shahi jeera"],
    pairs: ["Biryani", "Korma", "Nihari", "Festive gravies"],
    story:
      "Twenty-one spices, roasted in three separate batches so the delicate ones never scorch behind the bold ones. It is the blend the family has made for weddings since 1975 — and the reason the neighbours kept asking for a jar.",
    featured: true,
  },
  {
    slug: "shahi-paneer-masala",
    name: "Shahi",
    kind: "Paneer Masala",
    range: "heritage",
    tagline: "Velvet gravy, royal by descent.",
    hindi: "मलाई जैसी, शाही असली।",
    price: 195,
    size: "100 g",
    heat: 1,
    grind: "Fine, cold-milled",
    origin: "Lucknow",
    harvest: "Rabi 2026",
    icon: "cardamom",
    hue: ["#16523c", "#1e6b4c"],
    swatch: "#c98a2e",
    notes: ["Green cardamom", "Cashew", "Kasuri methi", "White pepper"],
    pairs: ["Shahi paneer", "Malai kofta", "Navratan korma"],
    story:
      "Built on cardamom rather than chilli — a gravy masala for people who want richness without the burn. Cold-milled so the volatile oils stay in the powder, not in the mill room.",
  },
  {
    slug: "kitchen-king",
    name: "Kitchen King",
    kind: "All-Purpose Masala",
    range: "heritage",
    tagline: "One blend, the whole raj.",
    hindi: "एक डिब्बा, पूरी रसोई।",
    badge: "Best seller",
    price: 210,
    size: "100 g",
    heat: 2,
    grind: "Medium",
    origin: "Malwa plateau",
    harvest: "Rabi 2026",
    icon: "jar",
    hue: ["#0e3b2c", "#4b5d22"],
    swatch: "#a8641c",
    notes: ["Coriander", "Cumin", "Fennel", "Dry ginger", "Bay"],
    pairs: ["Any sabzi", "Pulao", "Weeknight dal"],
    story:
      "The blend that covers the days you have not planned. Balanced enough for a dry sabzi, deep enough for a gravy — the one jar that earns its place at the front of the shelf.",
    featured: true,
  },
  {
    slug: "biryani-darbar",
    name: "Biryani Darbar",
    kind: "Dum Biryani Masala",
    range: "heritage",
    tagline: "Dum, layered like a court.",
    hindi: "हर परत में एक कहानी।",
    price: 245,
    size: "80 g",
    heat: 3,
    grind: "Coarse + fine, twin-milled",
    origin: "Hyderabad × Awadh",
    harvest: "Rabi 2026",
    icon: "bayLeaf",
    hue: ["#6f1a10", "#8b2517"],
    swatch: "#8b3a14",
    notes: ["Stone flower", "Star anise", "Kewra", "Green chilli", "Saffron"],
    pairs: ["Dum biryani", "Yakhni pulao", "Tehri"],
    story:
      "Twin-milled: the coarse fraction survives the dum and perfumes the rice, the fine fraction dissolves into the marinade. Two grinds, one packet — the reason home biryani finally tastes layered.",
  },
  {
    slug: "nawabi-meat-masala",
    name: "Nawabi",
    kind: "Meat Masala",
    range: "heritage",
    tagline: "Patience, ground fine.",
    hindi: "धीमी आँच, गहरा स्वाद।",
    price: 255,
    size: "100 g",
    heat: 4,
    grind: "Dark-roast, fine",
    origin: "Bhopal",
    harvest: "Rabi 2026",
    icon: "clove",
    hue: ["#241b13", "#6f1a10"],
    swatch: "#5c2a12",
    notes: ["Black stone flower", "Nutmeg", "Long pepper", "Roasted coriander"],
    pairs: ["Rogan josh", "Bhuna gosht", "Keema"],
    story:
      "Dark-roasted to the exact minute where coriander turns nutty and not bitter. The Bhopali kitchens that taught us this blend measure it in patience, not spoons.",
  },
  {
    slug: "sabut-khazana",
    name: "Sabut Khazana",
    kind: "Whole Spice Trio",
    range: "heritage",
    tagline: "Grind it yourself. We dare you.",
    hindi: "साबुत मसाले, असली ख़ज़ाना।",
    badge: "Gift-ready",
    price: 480,
    size: "3 × 50 g",
    heat: 1,
    grind: "Whole",
    origin: "Idukki · Coorg · Zanzibar route",
    harvest: "2026 lots",
    icon: "peppercorn",
    hue: ["#0e3b2c", "#241b13"],
    swatch: "#3d2b18",
    notes: ["Tellicherry black pepper", "Green cardamom", "Hand-picked clove"],
    pairs: ["Chai", "Tadka", "Your own garam masala"],
    story:
      "Three single-origin whole spices in a slip-lid tin — the sourcing story of the whole company in one box. If you want to know why our blends taste different, start here.",
    featured: true,
  },

  /* ── REGIONS ──────────────────────────────────────────── */
  {
    slug: "chappan-chhidkaav",
    name: "Chappan Chhidkaav",
    kind: "Indori Jeeravan",
    range: "regions",
    tagline: "Indori poha ki jaan.",
    hindi: "इंदौर, अब हर थाली में।",
    badge: "MP special",
    price: 175,
    size: "100 g",
    heat: 2,
    grind: "Street-style, hand-blended",
    origin: "Indore, Madhya Pradesh",
    harvest: "Rabi 2026",
    icon: "cumin",
    hue: ["#e58c1a", "#f2b30a"],
    swatch: "#d98c1f",
    notes: ["Fennel", "Dry mango", "Black salt", "Ajwain", "Turmeric"],
    pairs: ["Poha", "Sev", "Buttermilk", "Roasted corn"],
    story:
      "Named for Chhappan Dukaan, where fifty-six shops argue about the same breakfast. This is the sprinkle that decides the argument — sweet, sour, faintly bitter, and completely Indore.",
    featured: true,
  },
  {
    slug: "coal-hapuri",
    name: "Coal-hapuri",
    kind: "Kolhapuri Tarri Masala",
    range: "regions",
    tagline: "Rassa that runs red.",
    hindi: "तिखट, पण खरं.",
    badge: "Extra hot",
    price: 190,
    size: "100 g",
    heat: 5,
    grind: "Charcoal-roasted, coarse",
    origin: "Kolhapur, Maharashtra",
    harvest: "Kharif 2026",
    icon: "chilli",
    hue: ["#d93a22", "#6f1a10"],
    swatch: "#b32b16",
    notes: ["Sankeshwari chilli", "Byadgi chilli", "Dry coconut", "Stone flower"],
    pairs: ["Tambda rassa", "Mutton sukka", "Misal"],
    story:
      "Charcoal-roasted coconut is the whole trick — it gives the tarri its dark shine and stops the chilli from being merely loud. Five on our heat scale, and we are not exaggerating.",
    featured: true,
  },
  {
    slug: "bomb-bai",
    name: "Bomb Bai",
    kind: "Pav Bhaji Masala",
    range: "regions",
    tagline: "Chowpatty, on your tawa.",
    hindi: "बॉम्बे का स्वाद, घर की कढ़ाई में।",
    price: 165,
    size: "100 g",
    heat: 3,
    grind: "Fine",
    origin: "Mumbai",
    harvest: "Rabi 2026",
    icon: "flame",
    hue: ["#e58c1a", "#d93a22"],
    swatch: "#c9531c",
    notes: ["Amchur", "Kashmiri chilli", "Black salt", "Fennel", "Clove"],
    pairs: ["Pav bhaji", "Masala toast", "Tawa pulao"],
    story:
      "The masala that has to survive a slab of butter and still be tasted. We pushed the amchur up and the salt down, so you can season at the end like a real bhaji-wala.",
  },
  {
    slug: "banarasi-bawaal",
    name: "Banarasi Bawaal",
    kind: "Chaat Masala",
    range: "regions",
    tagline: "Ghat-side tang, bottled.",
    hindi: "एक छिड़काव, पूरा बनारस।",
    price: 145,
    size: "100 g",
    heat: 2,
    grind: "Fine, free-flow",
    origin: "Varanasi",
    harvest: "Rabi 2026",
    icon: "mustard",
    hue: ["#f2b30a", "#e58c1a"],
    swatch: "#c99a1e",
    notes: ["Black salt", "Amchur", "Pudina", "Ajwain", "Asafoetida"],
    pairs: ["Aloo chaat", "Fruit", "Buttermilk", "Fries"],
    story:
      "Sun-dried mint, not oven-dried — it keeps the green note that most chaat masalas cook out. Sprinkle it on anything you were about to eat plain.",
  },
  {
    slug: "chole-chaudhary",
    name: "Chole Chaudhary",
    kind: "Chole Masala",
    range: "regions",
    tagline: "Purani Dilli, under pressure.",
    hindi: "छोले ऐसे, कि पूरी कम पड़ जाए।",
    price: 175,
    size: "100 g",
    heat: 3,
    grind: "Dark-roast, medium",
    origin: "Old Delhi",
    harvest: "Rabi 2026",
    icon: "cinnamon",
    hue: ["#8b2517", "#d93a22"],
    swatch: "#7d3a1a",
    notes: ["Anardana", "Dried tea leaf", "Black cardamom", "Dry ginger"],
    pairs: ["Chole bhature", "Pindi chole", "Kulcha"],
    story:
      "Anardana for the sour, a whisper of tea leaf for the colour — the two things every Chandni Chowk halwai will refuse to admit to. We admit it, on the back of the pack.",
  },
  {
    slug: "malwa-dal-tadka",
    name: "Malwa Tadka",
    kind: "Dal Masala",
    range: "regions",
    tagline: "Har din ka perfect tadka.",
    hindi: "स्वाद भी, सेहत भी।",
    badge: "Everyday favourite",
    price: 155,
    size: "100 g",
    heat: 2,
    grind: "Medium",
    origin: "Malwa plateau, MP",
    harvest: "Rabi 2026",
    icon: "sprig",
    hue: ["#4b5d22", "#1e6b4c"],
    swatch: "#8a6a1e",
    notes: ["Cumin", "Hing", "Dry red chilli", "Kasuri methi", "Garlic"],
    pairs: ["Toor dal", "Dal bafla", "Khichdi", "Kadhi"],
    story:
      "One spoon into hot ghee and the whole building knows what you are cooking. Built for the dal you make four nights a week and never think about — until it is missing.",
    featured: true,
  },

  /* ── ESSENTIALS ───────────────────────────────────────── */
  {
    slug: "chutki-laal",
    name: "Chutki Laal",
    kind: "Kashmiri Mirch Powder",
    range: "essentials",
    tagline: "Ek chutki — full colour & fire.",
    hindi: "थोड़ा ही काफ़ी है।",
    badge: "New drop",
    price: 130,
    size: "200 g",
    heat: 3,
    grind: "Fine-milled",
    origin: "Byadgi, Karnataka",
    harvest: "Kharif 2026",
    icon: "chilli",
    hue: ["#d93a22", "#e8563a"],
    swatch: "#c02a12",
    notes: ["Byadgi chilli", "Kashmiri chilli"],
    pairs: ["Everything", "Tandoori marinades", "Rogan josh"],
    story:
      "Colour without carnage. Byadgi gives the deep lacquer red that makes a gravy look restaurant-made; the heat sits at a civil three so the whole table can eat.",
    featured: true,
  },
  {
    slug: "haldi-halla",
    name: "Haldi Halla",
    kind: "Turmeric Powder",
    range: "essentials",
    tagline: "Gold that stains and heals.",
    hindi: "रसोई का सोना।",
    price: 110,
    size: "200 g",
    heat: 0,
    grind: "Fine-milled",
    origin: "Nizamabad, Telangana",
    harvest: "2026 lot",
    icon: "turmeric",
    hue: ["#f2b30a", "#ffc740"],
    swatch: "#e0a10c",
    notes: ["Single-origin turmeric", "5.2% curcumin"],
    pairs: ["Dal", "Haldi doodh", "Every tadka"],
    story:
      "Lab-tested at 5.2% curcumin — roughly double the commodity average — because turmeric bought on price is turmeric bought on chalk.",
  },
  {
    slug: "dhaniya-dhamaal",
    name: "Dhaniya Dhamaal",
    kind: "Coriander Powder",
    range: "essentials",
    tagline: "The seed no one notices. The flavour no dish forgets.",
    hindi: "50 साल से एक ही तरीका।",
    price: 105,
    size: "200 g",
    heat: 0,
    grind: "Medium, cold-milled",
    origin: "Kota, Rajasthan",
    harvest: "Rabi 2026",
    icon: "coriander",
    hue: ["#4b5d22", "#1e6b4c"],
    swatch: "#9a8b2a",
    notes: ["Eagle-variety coriander seed"],
    pairs: ["Every gravy", "Sabzi", "Marinade base"],
    story:
      "The quiet one. It never gets named in the compliment, but take it out and the whole dish falls flat. Cold-milled below 40°C so the citrus oil never leaves the seed.",
    featured: true,
  },
  {
    slug: "hing-hero",
    name: "Hing Hero",
    kind: "Compounded Asafoetida",
    range: "essentials",
    tagline: "One pinch does all the talking.",
    hindi: "एक चुटकी, पूरा तड़का।",
    price: 165,
    size: "50 g",
    heat: 0,
    grind: "Granular",
    origin: "Hadda, via Afghanistan",
    harvest: "2026 lot",
    icon: "pinch",
    hue: ["#e58c1a", "#f2b30a"],
    swatch: "#b8791a",
    notes: ["Asafoetida resin", "Wheat flour", "Turmeric"],
    pairs: ["Dal", "Kadhi", "Sambar", "Pickles"],
    story:
      "Strong enough that the tin has to be double-sealed or your whole cupboard joins in. Used properly — one pinch, into hot fat, for two seconds — it does the work of an onion.",
  },
  {
    slug: "jeera-jhakaas",
    name: "Jeera Jhakaas",
    kind: "Roasted Cumin Powder",
    range: "essentials",
    tagline: "Roasted, not merely ground.",
    hindi: "भुना हुआ, तभी तो ज़बरदस्त।",
    price: 125,
    size: "150 g",
    heat: 1,
    grind: "Roasted, medium",
    origin: "Unjha, Gujarat",
    harvest: "Rabi 2026",
    icon: "cumin",
    hue: ["#8b2517", "#d93a22"],
    swatch: "#8a4a1c",
    notes: ["Single-origin cumin, pan-roasted"],
    pairs: ["Raita", "Chaas", "Jeera rice", "Salads"],
    story:
      "Roasted in small batches on an iron tawa until it smells like a summer afternoon, then ground warm. Raita without it is just curd.",
  },
  {
    slug: "express-everyday",
    name: "Express Everyday",
    kind: "Six-Sachet Starter",
    range: "essentials",
    tagline: "The whole spice box, in one hand.",
    hindi: "कम मसाला, पूरा स्वाद।",
    badge: "Quick-commerce",
    price: 199,
    size: "6 × 25 g",
    heat: 2,
    grind: "Mixed",
    origin: "Across the range",
    harvest: "2026 lots",
    icon: "jar",
    hue: ["#d93a22", "#e58c1a"],
    swatch: "#cf5a1e",
    notes: ["Chutki Laal", "Haldi Halla", "Dhaniya Dhamaal", "Malwa Tadka", "Jeera Jhakaas", "Kitchen King"],
    pairs: ["First kitchens", "Hostels", "Travel"],
    story:
      "For the flat you just moved into. Six sachets, ten minutes away, and enough to cook properly on day one instead of ordering in again.",
    featured: true,
  },
];

/* ── Helpers ──────────────────────────────────────────── */

export const getProduct = (slug) => PRODUCTS.find((p) => p.slug === slug);

export const productsByRange = (range) =>
  range === "all" ? PRODUCTS : PRODUCTS.filter((p) => p.range === range);

export const featuredProducts = () => PRODUCTS.filter((p) => p.featured);

export const relatedProducts = (product, limit = 3) =>
  PRODUCTS.filter((p) => p.range === product.range && p.slug !== product.slug).slice(0, limit);

export const formatPrice = (n) => `₹${n.toLocaleString("en-IN")}`;
