/**
 * Sunder Masala — catalogue + range taxonomy.
 * Three ranges, three appetites (per the brand strategy deck).
 */

import { fillFor, inkVariant } from "@/lib/color";

export const RANGES = {
  heritage: {
    id: "heritage",
    name: "Heritage",
    full: "Sunder Heritage",
    who: "The occasion cook",
    line: "From the courts of Awadh, to your table.",
    blurb:
      "Slow-ground, festive, inherited. Recipes handed down — never invented for a trend.",
    voice: ["Heritage", "Hereditary", "Confident", "Sourced"],
    bg: "var(--color-forest)",
    ink: "var(--color-ghee)",
    accent: "var(--color-marigold)",
    tw: { bg: "bg-forest", text: "text-ghee", accent: "text-marigold" },
    /* accent type, per the brand font spec */
    font: "font-heritage",
    icon: "starAnise",
  },
  regions: {
    id: "regions",
    name: "Regions",
    full: "Sunder Regions",
    who: "The rooted foodie",
    line: "Apna region, apni thali.",
    blurb:
      "Hyper-local blends you cannot find on a national shelf. One region, one hero dish, one masala.",
    voice: ["Sarcastic", "Punny", "Intentional"],
    bg: "var(--color-saffron)",
    ink: "var(--color-ink)",
    accent: "var(--color-oxblood)",
    tw: { bg: "bg-saffron", text: "text-ink", accent: "text-oxblood" },
    font: "font-regional",
    icon: "thela",
  },
  essentials: {
    id: "essentials",
    name: "Essentials",
    full: "Sunder Essentials · Express",
    who: "The everyday cook",
    line: "Ek chutki, full fire.",
    blurb:
      "Pure, potent, quick-commerce ready. The staple that lives at the front of the spice box.",
    voice: ["Fast", "Punny", "Pure"],
    bg: "var(--color-chilli)",
    ink: "var(--color-paper)",
    accent: "var(--color-marigold)",
    tw: { bg: "bg-chilli", text: "text-paper", accent: "text-marigold" },
    font: "font-poster",
    icon: "pinch",
  },
};

export const RANGE_LIST = [RANGES.heritage, RANGES.regions, RANGES.essentials];

export const PRODUCTS = [
  /* ── HERITAGE ─────────────────────────────────────────── */
  {
    slug: "darbari-garam-masala",
    name: "Darbari",
    kind: "Garam Masala",
    range: "heritage",
    tagline: "The crown of every royal dawat.",
    hindi: "दावत-ए-ख़ास, हर निवाले में।",
    badge: "Hero blend",
    price: 265,
    size: "100 g",
    heat: 2,
    grind: "Stone-ground, slow",
    origin: "Awadh × Malwa",
    harvest: "Rabi 2026",
    icon: "starAnise",
    hue: ["#0e3b2c", "#16523c"],
    swatch: "#7a4a12",
    notes: ["Black cardamom", "Cassia bark", "Mace", "Clove", "Shahi jeera"],
    pairs: ["Biryani", "Korma", "Nihari", "Festive gravies"],
    story:
      "Twenty-one spices, roasted in three separate batches so the delicate ones never scorch behind the bold ones. It is the blend the family has made for weddings since 1975 — and the reason the neighbours kept asking for a jar.",
    featured: true,
  },
  {
    slug: "shahi-paneer-masala",
    name: "Shahi",
    kind: "Paneer Masala",
    range: "heritage",
    tagline: "Velvet gravy, royal by descent.",
    hindi: "मलाई जैसी, शाही असली।",
    price: 195,
    size: "100 g",
    heat: 1,
    grind: "Fine, cold-milled",
    origin: "Lucknow",
    harvest: "Rabi 2026",
    icon: "cardamom",
    hue: ["#16523c", "#1e6b4c"],
    swatch: "#c98a2e",
    notes: ["Green cardamom", "Cashew", "Kasuri methi", "White pepper"],
    pairs: ["Shahi paneer", "Malai kofta", "Navratan korma"],
    story:
      "Built on cardamom rather than chilli — a gravy masala for people who want richness without the burn. Cold-milled so the volatile oils stay in the powder, not in the mill room.",
  },
  {
    slug: "kitchen-king",
    name: "Kitchen King",
    kind: "All-Purpose Masala",
    range: "heritage",
    tagline: "One blend, the whole raj.",
    hindi: "एक डिब्बा, पूरी रसोई।",
    badge: "Best seller",
    price: 210,
    size: "100 g",
    heat: 2,
    grind: "Medium",
    origin: "Malwa plateau",
    harvest: "Rabi 2026",
    icon: "jar",
    hue: ["#0e3b2c", "#4b5d22"],
    swatch: "#a8641c",
    notes: ["Coriander", "Cumin", "Fennel", "Dry ginger", "Bay"],
    pairs: ["Any sabzi", "Pulao", "Weeknight dal"],
    story:
      "The blend that covers the days you have not planned. Balanced enough for a dry sabzi, deep enough for a gravy — the one jar that earns its place at the front of the shelf.",
    featured: true,
  },
  {
    slug: "biryani-darbar",
    name: "Biryani Darbar",
    kind: "Dum Biryani Masala",
    range: "heritage",
    tagline: "Dum, layered like a court.",
    hindi: "हर परत में एक कहानी।",
    price: 245,
    size: "80 g",
    heat: 3,
    grind: "Coarse + fine, twin-milled",
    origin: "Hyderabad × Awadh",
    harvest: "Rabi 2026",
    icon: "bayLeaf",
    hue: ["#6f1a10", "#8b2517"],
    swatch: "#8b3a14",
    notes: ["Stone flower", "Star anise", "Kewra", "Green chilli", "Saffron"],
    pairs: ["Dum biryani", "Yakhni pulao", "Tehri"],
    story:
      "Twin-milled: the coarse fraction survives the dum and perfumes the rice, the fine fraction dissolves into the marinade. Two grinds, one packet — the reason home biryani finally tastes layered.",
  },
  {
    slug: "nawabi-meat-masala",
    name: "Nawabi",
    kind: "Meat Masala",
    range: "heritage",
    tagline: "Patience, ground fine.",
    hindi: "धीमी आँच, गहरा स्वाद।",
    price: 255,
    size: "100 g",
    heat: 4,
    grind: "Dark-roast, fine",
    origin: "Bhopal",
    harvest: "Rabi 2026",
    icon: "clove",
    hue: ["#241b13", "#6f1a10"],
    swatch: "#5c2a12",
    notes: ["Black stone flower", "Nutmeg", "Long pepper", "Roasted coriander"],
    pairs: ["Rogan josh", "Bhuna gosht", "Keema"],
    story:
      "Dark-roasted to the exact minute where coriander turns nutty and not bitter. The Bhopali kitchens that taught us this blend measure it in patience, not spoons.",
  },
  {
    slug: "sabut-khazana",
    name: "Sabut Khazana",
    kind: "Whole Spice Trio",
    range: "heritage",
    tagline: "Grind it yourself. We dare you.",
    hindi: "साबुत मसाले, असली ख़ज़ाना।",
    badge: "Gift-ready",
    price: 480,
    size: "3 × 50 g",
    heat: 1,
    grind: "Whole",
    origin: "Idukki · Coorg · Zanzibar route",
    harvest: "2026 lots",
    icon: "peppercorn",
    hue: ["#0e3b2c", "#241b13"],
    swatch: "#3d2b18",
    notes: ["Tellicherry black pepper", "Green cardamom", "Hand-picked clove"],
    pairs: ["Chai", "Tadka", "Your own garam masala"],
    story:
      "Three single-origin whole spices in a slip-lid tin — the sourcing story of the whole company in one box. If you want to know why our blends taste different, start here.",
    featured: true,
  },

  /* ── REGIONS ──────────────────────────────────────────── */
  {
    slug: "chappan-chhidkaav",
    name: "Chappan Chhidkaav",
    kind: "Indori Jeeravan",
    range: "regions",
    tagline: "Indori poha ki jaan.",
    hindi: "इंदौर, अब हर थाली में।",
    badge: "MP special",
    price: 175,
    size: "100 g",
    heat: 2,
    grind: "Street-style, hand-blended",
    origin: "Indore, Madhya Pradesh",
    harvest: "Rabi 2026",
    icon: "cumin",
    hue: ["#e58c1a", "#f2b30a"],
    swatch: "#d98c1f",
    notes: ["Fennel", "Dry mango", "Black salt", "Ajwain", "Turmeric"],
    pairs: ["Poha", "Sev", "Buttermilk", "Roasted corn"],
    story:
      "Named for Chhappan Dukaan, where fifty-six shops argue about the same breakfast. This is the sprinkle that decides the argument — sweet, sour, faintly bitter, and completely Indore.",
    featured: true,
  },
  {
    slug: "coal-hapuri",
    name: "Coal-hapuri",
    kind: "Kolhapuri Tarri Masala",
    range: "regions",
    tagline: "Rassa that runs red.",
    hindi: "तिखट, पण खरं.",
    badge: "Extra hot",
    price: 190,
    size: "100 g",
    heat: 5,
    grind: "Charcoal-roasted, coarse",
    origin: "Kolhapur, Maharashtra",
    harvest: "Kharif 2026",
    icon: "chilli",
    hue: ["#d93a22", "#6f1a10"],
    swatch: "#b32b16",
    notes: ["Sankeshwari chilli", "Byadgi chilli", "Dry coconut", "Stone flower"],
    pairs: ["Tambda rassa", "Mutton sukka", "Misal"],
    story:
      "Charcoal-roasted coconut is the whole trick — it gives the tarri its dark shine and stops the chilli from being merely loud. Five on our heat scale, and we are not exaggerating.",
    featured: true,
  },
  {
    slug: "bomb-bai",
    name: "Bomb Bai",
    kind: "Pav Bhaji Masala",
    range: "regions",
    tagline: "Chowpatty, on your tawa.",
    hindi: "बॉम्बे का स्वाद, घर की कढ़ाई में।",
    price: 165,
    size: "100 g",
    heat: 3,
    grind: "Fine",
    origin: "Mumbai",
    harvest: "Rabi 2026",
    icon: "flame",
    hue: ["#e58c1a", "#d93a22"],
    swatch: "#c9531c",
    notes: ["Amchur", "Kashmiri chilli", "Black salt", "Fennel", "Clove"],
    pairs: ["Pav bhaji", "Masala toast", "Tawa pulao"],
    story:
      "The masala that has to survive a slab of butter and still be tasted. We pushed the amchur up and the salt down, so you can season at the end like a real bhaji-wala.",
  },
  {
    slug: "banarasi-bawaal",
    name: "Banarasi Bawaal",
    kind: "Chaat Masala",
    range: "regions",
    tagline: "Ghat-side tang, bottled.",
    hindi: "एक छिड़काव, पूरा बनारस।",
    price: 145,
    size: "100 g",
    heat: 2,
    grind: "Fine, free-flow",
    origin: "Varanasi",
    harvest: "Rabi 2026",
    icon: "mustard",
    hue: ["#f2b30a", "#e58c1a"],
    swatch: "#c99a1e",
    notes: ["Black salt", "Amchur", "Pudina", "Ajwain", "Asafoetida"],
    pairs: ["Aloo chaat", "Fruit", "Buttermilk", "Fries"],
    story:
      "Sun-dried mint, not oven-dried — it keeps the green note that most chaat masalas cook out. Sprinkle it on anything you were about to eat plain.",
  },
  {
    slug: "chole-chaudhary",
    name: "Chole Chaudhary",
    kind: "Chole Masala",
    range: "regions",
    tagline: "Purani Dilli, under pressure.",
    hindi: "छोले ऐसे, कि पूरी कम पड़ जाए।",
    price: 175,
    size: "100 g",
    heat: 3,
    grind: "Dark-roast, medium",
    origin: "Old Delhi",
    harvest: "Rabi 2026",
    icon: "cinnamon",
    hue: ["#8b2517", "#d93a22"],
    swatch: "#7d3a1a",
    notes: ["Anardana", "Dried tea leaf", "Black cardamom", "Dry ginger"],
    pairs: ["Chole bhature", "Pindi chole", "Kulcha"],
    story:
      "Anardana for the sour, a whisper of tea leaf for the colour — the two things every Chandni Chowk halwai will refuse to admit to. We admit it, on the back of the pack.",
  },
  {
    slug: "malwa-dal-tadka",
    name: "Malwa Tadka",
    kind: "Dal Masala",
    range: "regions",
    tagline: "Har din ka perfect tadka.",
    hindi: "स्वाद भी, सेहत भी।",
    badge: "Everyday favourite",
    price: 155,
    size: "100 g",
    heat: 2,
    grind: "Medium",
    origin: "Malwa plateau, MP",
    harvest: "Rabi 2026",
    icon: "sprig",
    hue: ["#4b5d22", "#1e6b4c"],
    swatch: "#8a6a1e",
    notes: ["Cumin", "Hing", "Dry red chilli", "Kasuri methi", "Garlic"],
    pairs: ["Toor dal", "Dal bafla", "Khichdi", "Kadhi"],
    story:
      "One spoon into hot ghee and the whole building knows what you are cooking. Built for the dal you make four nights a week and never think about — until it is missing.",
    featured: true,
  },

  /* ── ESSENTIALS ───────────────────────────────────────────
     The live catalogue: single-ingredient powders, real SKUs,
     sizes and prices from sundermasala.com. Descriptions are the
     brand's own copy, tightened. */
  {
    slug: "lal-mirch-powder",
    name: "Lal Mirch",
    kind: "Red Chilli Powder",
    range: "essentials",
    tagline: "Ek chutki, full fire.",
    hindi: "थोड़ी सी, पूरी आग।",
    badge: "Best seller",
    price: 46,
    size: "100 g",
    heat: 4,
    grind: "Fine-milled",
    origin: "Guntur, Andhra Pradesh",
    harvest: "Kharif 2026",
    icon: "chilli",
    hue: ["#d03821", "#e8563a"],
    swatch: "#c02a12",
    notes: ["Whole dried red chilli"],
    pairs: ["Dal", "Vegetables", "Meat preparations"],
    story:
      "Natural red chilli powder, made from top-notch quality red chillies sourced from the best farms — with the best aroma the spice can give. No preservatives, no colours, no artificial flavours. Use it in the dal, the vegetables, the meat, and every other delicacy in the kitchen.",
    featured: true,
  },
  {
    slug: "haldi-powder",
    name: "Haldi",
    kind: "Turmeric Powder",
    range: "essentials",
    tagline: "Rasoi ka sona.",
    hindi: "रसोई का सोना।",
    price: 24,
    size: "100 g",
    heat: 0,
    grind: "Fine-milled",
    origin: "Nizamabad, Telangana",
    harvest: "2026 lot",
    icon: "turmeric",
    hue: ["#f2b30a", "#ffc740"],
    swatch: "#e0a10c",
    notes: ["100% turmeric, nothing else"],
    pairs: ["Dal", "Haldi doodh", "Every tadka"],
    story:
      "Enjoy the rich taste of Sunder Turmeric Powder in all your favourite dishes — 100% natural, pure and healthy. A very soft-textured powder with high nutritional value that also boosts the immune system. No preservations, no colours, no artificial flavours.",
    featured: true,
  },
  {
    slug: "dhaniya-powder",
    name: "Dhaniya",
    kind: "Coriander Powder",
    range: "essentials",
    tagline: "The seed no one notices. The flavour no dish forgets.",
    hindi: "हर ग्रेवी की बुनियाद।",
    price: 29,
    size: "100 g",
    heat: 0,
    grind: "Soft-textured, cold-milled",
    origin: "Kota, Rajasthan",
    harvest: "Rabi 2026",
    icon: "coriander",
    hue: ["#4b5d22", "#1e6b4c"],
    swatch: "#9a8b2a",
    notes: ["Whole coriander seed"],
    pairs: ["Every gravy", "Sabzi", "Marinade base"],
    story:
      "Sunder Coriander Powder is rich in flavour and taste — a must-have ingredient that gives a distinct aroma and colour to your dishes. A very soft-textured powder with high nutritional value. No preservations, no colours, no artificial flavours.",
    featured: true,
  },
  {
    slug: "kashmiri-mirchi-powder",
    name: "Kashmiri Mirchi",
    kind: "Kashmiri Chilli Powder",
    range: "essentials",
    tagline: "All the colour. Almost none of the fight.",
    hindi: "रंग पूरा, तीखा ज़रा भी नहीं।",
    price: 98,
    size: "100 g",
    heat: 1,
    grind: "Fine-milled",
    origin: "Byadgi, Karnataka",
    harvest: "Kharif 2026",
    icon: "chilli",
    hue: ["#b4301c", "#d03821"],
    swatch: "#a8291a",
    notes: ["Kashmiri chilli"],
    pairs: ["Tandoori marinades", "Rogan josh", "Restaurant-red gravies"],
    story:
      "Negligible pungency and rich in flavour. Our Kashmiri Chilli Powder gives a deep red colour to the dish and complements every cuisine — it is used for its colour, and does not add much heat. No preservations, no colours, no artificial flavours.",
  },
  {
    slug: "kali-mirch-powder",
    name: "Kali Mirch",
    kind: "Black Pepper Powder",
    range: "essentials",
    tagline: "The table's oldest argument-settler.",
    hindi: "हर मेज़ पर, हर वक़्त।",
    price: 160,
    size: "100 g",
    heat: 3,
    grind: "Ground fine",
    origin: "Idukki, Kerala",
    harvest: "2026 lot",
    icon: "peppercorn",
    hue: ["#241b13", "#4a3a29"],
    swatch: "#3a2c1f",
    notes: ["100% black peppercorns, high piperine"],
    pairs: ["Soups", "Salads", "Anything at the table"],
    story:
      "A staple dinner-table condiment: 100% pure black peppercorns, ground. Made from the best quality, high-piperine peppercorns — higher piperine, more heat. No preservations, no colours, no artificial flavours.",
  },
  {
    slug: "safed-mirch-powder",
    name: "Safed Mirch",
    kind: "White Pepper Powder",
    range: "essentials",
    tagline: "Heat you taste but never see.",
    hindi: "दिखे नहीं, लगे ज़रूर।",
    price: 260,
    size: "100 g",
    heat: 3,
    grind: "Ground fine",
    origin: "Idukki, Kerala",
    harvest: "2026 lot",
    icon: "peppercorn",
    hue: ["#c9a97b", "#ebdcbd"],
    swatch: "#8a7148",
    notes: ["Unbleached natural white pepper"],
    pairs: ["White gravies", "Soups", "Indo-Chinese"],
    story:
      "Unbleached, natural white pepper sourced directly from the farmers, then washed, dried, dehydrated and held at controlled humidity and temperature before packing. No preservations, no colours, no artificial flavours.",
  },
  {
    slug: "sunth-powder",
    name: "Sunth",
    kind: "Dry Ginger Powder",
    range: "essentials",
    tagline: "Winter in a spoon.",
    hindi: "सर्दी का इलाज, रसोई में।",
    price: 76,
    size: "100 g",
    heat: 2,
    grind: "Fine-milled",
    origin: "Kochi, Kerala",
    harvest: "2026 lot",
    icon: "sprig",
    hue: ["#b36d14", "#e58c1a"],
    swatch: "#8c5510",
    notes: ["Certified organic dry ginger"],
    pairs: ["Chai", "Gingerbread", "Kadha"],
    story:
      "A 100% certified organic product — every Sunder organic line can be traced back to its origin. Use it as a seasoning while preparing gingerbread, cakes, cookies and ginger beer. No preservations, no colours, no artificial flavours.",
  },
  {
    slug: "amchur-powder",
    name: "Amchur",
    kind: "Dried Mango Powder",
    range: "essentials",
    tagline: "Sourness without the squeeze.",
    hindi: "खटास, बिना निचोड़े।",
    price: 35,
    size: "100 g",
    heat: 0,
    grind: "Fine-milled",
    origin: "Malwa, Madhya Pradesh",
    harvest: "2026 lot",
    icon: "jar",
    hue: ["#e58c1a", "#f2b30a"],
    swatch: "#8c5510",
    notes: ["Sun-dried raw mango"],
    pairs: ["Curries", "Chutneys", "Soups", "Marinades"],
    story:
      "Veg and non-veg dishes are both lifted by amchur. It has tenderising qualities similar to lime and lemon juice, and adds more flavour to curries, chutneys, soups and marinades — without thinning the gravy the way juice does.",
  },
  {
    slug: "kuti-teja-mirch",
    name: "Kuti Teja",
    kind: "Crushed Teja Chilli",
    range: "essentials",
    tagline: "For the ones who ask for it hotter.",
    hindi: "और तीखा? ये लीजिए।",
    badge: "Extra hot",
    price: 202,
    size: "500 g",
    heat: 5,
    grind: "Coarse-crushed",
    origin: "Khammam, Telangana",
    harvest: "Kharif 2026",
    icon: "flame",
    hue: ["#8b2517", "#d03821"],
    swatch: "#8b2517",
    notes: ["Crushed Teja chilli"],
    pairs: ["Tadka", "Pickles", "Anything that needs shouting at"],
    story:
      "Fresh, healthy and 100% natural. Organic red Kuti Teja mirchi has a unique flavour — naturally rich and smooth, perfectly balanced, with a nice coarse texture. It is used to add heat and spice to a dish. No artificial colours, no added preservatives.",
  },
  {
    slug: "sunder-garam-masala",
    name: "Garam Masala",
    kind: "Garam Masala Powder",
    range: "essentials",
    tagline: "The one jar every kitchen already trusts.",
    hindi: "हर रसोई का भरोसा।",
    price: 70,
    size: "100 g",
    heat: 3,
    grind: "Slow-ground",
    origin: "Blended in Indore",
    harvest: "2026 lots",
    icon: "starAnise",
    hue: ["#6f1a10", "#8b2517"],
    swatch: "#6f1a10",
    notes: ["A unique blend of warm spices"],
    pairs: ["Curries", "Vegetables", "Dinner, most nights"],
    story:
      "The perfect spice mix for all your Indian cooking — a unique blend carefully crafted over decades. Deeper in colour and spicier in taste, it is the right addition to any curry and good on everything from vegetables to salads, adding a burst of flavour to every dish.",
    featured: true,
  },
];

/* ── Derived accessible colours ───────────────────────────
   `hue` is tuned for fills. Text needs different values, so derive them
   once here rather than eyeballing a second hex per product. */
for (const p of PRODUCTS) {
  // The hue as readable text on cream — also doubles as a dark fill for pills.
  p.hueInk = inkVariant(p.hue[0], 4.5);
  // Hero gradient, deepened so light type stays legible on the yellow blends.
  p.hueFill = [fillFor(p.hue[0], 4.6), fillFor(p.hue[1], 4.6)];
}

/* ── Helpers ──────────────────────────────────────────── */

export const getProduct = (slug) => PRODUCTS.find((p) => p.slug === slug);

export const productsByRange = (range) =>
  range === "all" ? PRODUCTS : PRODUCTS.filter((p) => p.range === range);

export const featuredProducts = () => PRODUCTS.filter((p) => p.featured);

export const relatedProducts = (product, limit = 3) =>
  PRODUCTS.filter((p) => p.range === product.range && p.slug !== product.slug).slice(0, limit);

export const formatPrice = (n) => `₹${n.toLocaleString("en-IN")}`;
